### ISSUE TITLE
ECSのDecidimServiceがDBへの接続に失敗して起動しない

### ISSUE THREAD

**Issue by yousan** [codeforjapan/decidim-cfj-cdk#46]
## 改善詳細 / Details of Improvement
- ECSのDecidimServiceがDBへの接続に失敗します。
- 原因はDecidimの config/database.yaml で develop（default）が参照する環境変数が違うことにあるようです。

### 該当箇所

[decidim-cfj/config/database.yml](https://github.com/codeforjapan/decidim-cfj/blob/5af68566a977771a7d759557027e2713b6990309/config/database.yml#L19-L32)

```
 default: &default 
   adapter: postgresql 
   encoding: unicode 
   # For details on connection pooling, see rails configuration guide 
   # http://guides.rubyonrails.org/configuring.html#database-pooling 
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> 
   host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %> 
   port: <%= ENV.fetch("DATABASE_PORT") { "5432" } %> 
   username: <%= ENV.fetch("DATABASE_USERNAME") { "" } %> 
   password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %> 
  
 development: 
   <<: *default
  database: <%= ENV.fetch("DATABASE_DBNAME_DEV") { "decidim-app_development" } %>
```

Productionでは `RDS_DB_*` を参照しています。
[decidim-cfj/config/database.yml](https://github.com/codeforjapan/decidim-cfj/blob/5af68566a977771a7d759557027e2713b6990309/config/database.yml#L87-L95)

```
production:
    <<: *default
    adapter: postgresql
    encoding: unicode
    database: <%= ENV['RDS_DB_NAME'] %>
    username: <%= ENV['RDS_USERNAME'] %>
    password: <%= ENV['RDS_PASSWORD'] %>
    host: <%= ENV['RDS_HOSTNAME'] %>
    port: <%= ENV['RDS_PORT'] %>
```

## スクリーンショットなど / Screenshot
ECSでDB接続に失敗している箇所のログです。

![image (9)](https://github.com/codeforjapan/decidim-cfj-cdk/assets/561613/d2b826a5-d4f4-4123-9702-324b18046834)

## 期待する見せ方・挙動 / Expected behavior
- DBに接続してECSのサービスが起動できること
